namespace LeetU.Data.Entities
{
    /// <summary>
    /// An entity. Represents a row in the database. It can also represent a return from a stored procedure. There is no need to alter this as it is auto generated by the context builder
    /// </summary>
    public partial class Address
    {
        public Address()
        {
            Students = new HashSet<Student>();
        }

        public long Id { get; set; }
        public string AddressLine1 { get; set; } = null!;
        public string? AddressLine2 { get; set; }
        public string? AddressLine3 { get; set; }
        public string? Town { get; set; }
        public string? County { get; set; }
        public string? PostCode { get; set; }

        public virtual ICollection<Student> Students { get; set; }
    }
}
