namespace LeetU.Data.Entities
{
    /// <summary>
    /// An entity. Represents a row in the database. It can also represent a return from a stored procedure. There is no need to alter this as it is auto generated by the context builder
    /// </summary>
    public partial class StudentCourse
    {
        public long Id { get; set; }
        public long StudentId { get; set; }
        public long CourseId { get; set; }

        public virtual Course Course { get; set; } = null!;
        public virtual Student Student { get; set; } = null!;
    }
}
