namespace LeetU.Data.Entities
{
    /// <summary>
    /// An entity. Represents a row in the database. It can also represent a return from a stored procedure. There is no need to alter this as it is auto generated by the context builder
    /// </summary>
    public partial class Student
    {
        public Student()
        {
            StudentCourses = new HashSet<StudentCourse>();
        }

        public long Id { get; set; }
        public string Name { get; set; } = null!;
        public string Surname { get; set; } = null!;
        public string DateOfBirth { get; set; } = null!;
        public long Sex { get; set; }
        public long AddressId { get; set; }

        public virtual Address Address { get; set; } = null!;
        public virtual ICollection<StudentCourse> StudentCourses { get; set; }
    }
}
